"""Generate PROJECT_STATUS.md from filesystem and research/deep_dives.csv.

Single command to regenerate all dynamic project documentation:
    uv run python scripts/sync_project_status.py

The output file (PROJECT_STATUS.md) is referenced by CLAUDE.md via @-include
so that Claude Code always sees current project state without manual edits.
"""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOKS_DIR = ROOT / "notebooks"
SRC_DIR = ROOT / "src"
CSV_PATH = ROOT / "research" / "deep_dives.csv"
OUTPUT_PATH = ROOT / "PROJECT_STATUS.md"
PYPROJECT_PATH = ROOT / "pyproject.toml"


def read_case_studies() -> list[dict[str, str]]:
    """Read case studies from the single source of truth CSV."""
    with CSV_PATH.open() as f:
        return list(csv.DictReader(f))


def scan_notebooks() -> dict[str, list[str]]:
    """Scan notebook directories and return {dir_name: [notebook_files]}."""
    result: dict[str, list[str]] = {}
    for d in sorted(NOTEBOOKS_DIR.iterdir()):
        if d.is_dir() and d.name.startswith("dd"):
            notebooks = sorted(p.name for p in d.glob("*.py") if not p.name.startswith("_"))
            if notebooks:
                result[d.name] = notebooks
    return result


def scan_archive() -> dict[str, list[str]]:
    """Scan archived notebook directories."""
    archive_dir = NOTEBOOKS_DIR / "_archive"
    result: dict[str, list[str]] = {}
    if archive_dir.exists():
        for d in sorted(archive_dir.iterdir()):
            if d.is_dir() and d.name.startswith("dd"):
                notebooks = sorted(p.name for p in d.glob("*.py") if not p.name.startswith("_"))
                if notebooks:
                    result[d.name] = notebooks
    return result


def scan_src_modules() -> list[str]:
    """Scan src/ for Python modules."""
    modules = []
    for p in sorted(SRC_DIR.rglob("*.py")):
        rel = p.relative_to(SRC_DIR)
        if rel.name == "__init__.py":
            continue
        modules.append(f"src/{rel}")
    return modules


def read_dependencies() -> list[str]:
    """Extract dependencies from pyproject.toml (skip comments)."""
    deps = []
    in_deps = False
    for line in PYPROJECT_PATH.read_text().splitlines():
        if line.strip() == "dependencies = [":
            in_deps = True
            continue
        if in_deps:
            if line.strip() == "]":
                break
            cleaned = line.strip().strip(",").strip('"').strip("'")
            if cleaned and not cleaned.startswith("#"):
                deps.append(cleaned)
    return deps


def generate() -> str:
    """Generate the full PROJECT_STATUS.md content."""
    studies = read_case_studies()
    active_notebooks = scan_notebooks()
    archived = scan_archive()
    src_modules = scan_src_modules()
    deps = read_dependencies()

    lines: list[str] = []
    lines.append(f"<!-- Auto-generated by scripts/sync_project_status.py on {date.today()} -->")
    lines.append(f"<!-- Do not edit manually — run: uv run python scripts/sync_project_status.py -->")
    lines.append("")
    lines.append("# Project Status")
    lines.append("")

    # --- Case Studies ---
    lines.append("## Case Studies")
    lines.append("")
    lines.append("Source: `research/deep_dives.csv`")
    lines.append("")
    lines.append("| ID | Focus | Topic | Status |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for s in studies:
        lines.append(f"| {s['ID']} | {s['Focus Area']} | {s['Topic']} | {s['Status']} |")
    lines.append("")

    # --- Active Notebooks ---
    lines.append("## Active Notebooks")
    lines.append("")
    if active_notebooks:
        for dir_name, files in active_notebooks.items():
            # Find matching case study
            match = next((s for s in studies if s.get("Notebook Dir") == dir_name), None)
            label = match["Topic"] if match else dir_name
            lines.append(f"### `notebooks/{dir_name}/` — {label}")
            lines.append("")
            for f in files:
                lines.append(f"- `{f}`")
            lines.append("")
    else:
        lines.append("No active notebooks found.")
        lines.append("")

    # --- Archived ---
    if archived:
        lines.append("## Archived Notebooks")
        lines.append("")
        for dir_name, files in archived.items():
            match = next((s for s in studies if s.get("Notebook Dir") == f"_archive/{dir_name}"), None)
            label = match["Topic"] if match else dir_name
            lines.append(f"- `notebooks/_archive/{dir_name}/` — {label} ({len(files)} notebooks)")
        lines.append("")

    # --- Source Modules ---
    lines.append("## Source Modules")
    lines.append("")
    for mod in src_modules:
        lines.append(f"- `{mod}`")
    lines.append("")

    # --- Dependencies ---
    lines.append("## Dependencies")
    lines.append("")
    lines.append("Source: `pyproject.toml`")
    lines.append("")
    for dep in deps:
        lines.append(f"- {dep}")
    lines.append("")

    # --- Project Tree (stable structure only) ---
    lines.append("## Project Structure")
    lines.append("")
    lines.append("```")
    lines.append("Systems/")
    lines.append("├── CLAUDE.md                    # Project rules and agent config")
    lines.append("├── PROJECT_STATUS.md            # Auto-generated (this file)")
    lines.append("├── pyproject.toml               # Dependencies (uv managed)")
    lines.append("├── research-framework.md        # Analytical framework and references")
    lines.append("│")
    lines.append("├── src/                         # Reusable Python code")

    # Group src modules by subdirectory
    top_level = [m for m in src_modules if "/" not in m.replace("src/", "")]
    sub_dirs: dict[str, list[str]] = {}
    for m in src_modules:
        rel = m.replace("src/", "")
        if "/" in rel:
            d = rel.split("/")[0]
            sub_dirs.setdefault(d, []).append(rel)

    for m in top_level:
        lines.append(f"│   ├── {m.replace('src/', '')}")
    for d, files in sorted(sub_dirs.items()):
        lines.append(f"│   └── {d}/")
        for f in files:
            lines.append(f"│       └── {f.split('/')[-1]}")

    lines.append("│")
    lines.append("├── notebooks/                   # Marimo notebooks (.py)")

    for dir_name, files in active_notebooks.items():
        lines.append(f"│   ├── {dir_name}/")
        for f in files:
            lines.append(f"│   │   ├── {f}")
    if archived:
        lines.append("│   ├── _archive/                # Not publication-ready")
    lines.append("│   └── images/                  # Generated figures")

    lines.append("│")
    lines.append("├── research/                    # Case study metadata")
    lines.append("│   └── deep_dives.csv           # Single source of truth")
    lines.append("│")
    lines.append("├── scripts/                     # Project tooling")
    lines.append("│   └── sync_project_status.py   # Generates this file")
    lines.append("│")
    lines.append("├── data/                        # Not in git")
    lines.append("└── .claude/agents/              # Specialized sub-agents")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    content = generate()
    OUTPUT_PATH.write_text(content)
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)}")
