"""Compatibility shim — delegates to the flowmpl package.

All symbols previously defined here are now canonical in flowmpl.
This shim exists so existing notebook imports continue to work unchanged.
"""

from flowmpl import (  # noqa: F401
    BAR_DEFAULTS,
    CATEGORICAL,
    COLORS,
    COMPANY_COLORS,
    COMPANY_LABELS,
    CONTEXT,
    FIGSIZE,
    FLOW_FONT_SIZE,
    FONTS,
    FUEL_COLORS,
    INK,
    INK_LIGHT,
    INK_MID,
    LEGEND_DEFAULTS,
    PAPER,
    RULE,
    SCATTER_DEFAULTS,
    add_rule,
    add_source,
    annotate_point,
    annotated_series,
    apply_style,
    chart_title,
    company_color,
    company_label,
    flow_diagram,
    focus_colors,
    fuel_color,
    horizontal_bar_ranking,
    legend_below,
    multi_panel,
    reference_line,
    stacked_bar,
    us_scatter_map,
    waterfall_chart,
)

__all__ = [
    "apply_style",
    "BAR_DEFAULTS",
    "CATEGORICAL",
    "COLORS",
    "COMPANY_COLORS",
    "COMPANY_LABELS",
    "CONTEXT",
    "FIGSIZE",
    "FLOW_FONT_SIZE",
    "FONTS",
    "FUEL_COLORS",
    "INK",
    "INK_LIGHT",
    "INK_MID",
    "LEGEND_DEFAULTS",
    "PAPER",
    "RULE",
    "SCATTER_DEFAULTS",
    "add_rule",
    "add_source",
    "annotate_point",
    "annotated_series",
    "chart_title",
    "company_color",
    "company_label",
    "flow_diagram",
    "focus_colors",
    "fuel_color",
    "horizontal_bar_ranking",
    "legend_below",
    "multi_panel",
    "reference_line",
    "stacked_bar",
    "us_scatter_map",
    "waterfall_chart",
]
